### ISSUE TITLE
Local project setup

### ISSUE THREAD

**Issue by GrawtoG** [DaniDevy/LudumDare45#1]
Hi,
I've cloned your project and I'm trying to open in Unity but it simply don't work. Could you help me with this? Maybe there are some files missing? I'm using Unity version 2018.4.21f1 
Thanks

**Comment by mandar1jn** [comment]
That is right. He is not sharing the whole project. Only the assets

**Comment by AngusBrowning-Programmer1** [comment]
Yeah

**Comment by pranshu05** [comment]
lol
